### PR TITLE
Add docs theme

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Integrate docs-vanilla-theme 0.2.0
- Change mark-up to match the new theme

## QA
- Load vf.io
- Click through and check its styled with the docs theme

Fixes: https://github.com/ubuntudesign/vanillaframework.io/issues/17

### CODE REVIEW

**Comment by barrymcgee** [comment]
@anthonydillon Nav accordion still not working? http://recordit.co/NmQvfIYpbG

**Comment by anthonydillon** [comment]
Thanks @barrymcgee this one is blocked on https://github.com/ubuntudesign/docs-vanilla-theme/pull/11

**Comment by deadlight** [comment]
@anthonydillon looks like the blocker is removed, can we make any progress here?

**Comment by pmahnke** [comment]
@deadlight I should have added a comment, but I tested this earlier and the accordion didn't open with a click on the down arrow and the styles from vanilla where being overwritten for patterns/buttons (meaning they were all orange)

so please retest that if you are looking now.

**Comment by deadlight** [comment]
@anthonydillon: I tested in Ubuntu Chrome/FF. The accordion works BUT if you click on the arrow icon (the :after element) the click event doesn't trigger.

**Comment by anthonydillon** [comment]
Ah ok, will pick up first thing in the morning.

**Comment by anthonydillon** [comment]
@deadlight @pmahnke Good spot with the chevron. This is ready for another review when you have a min.

**Pull request merged**
